version: "3.8"

# docker run -it --rm --name test -v ".:/app" -w /app -v "site-packages:/usr/local/lib/python3.9/site-packages" -v "pip-cache:/root/.cache/pip/" python:3.9.18-alpine3.18 sh

# docker compose build
# docker compose up
# docker compose down
# docker compose logs backend
# docker compose exec -it backend sh

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: backend:v1
    container_name: backend
    environment:
      APP_LISTEN_HOST: "0.0.0.0"
      APP_LISTEN_PORT: 5000
      APP_DOTENV_PATH: .env.dev
    ports:
      - 8000:5000
    networks:
      - app

networks:
  app:
