@protocol=http
@host=localhost
@port=5000
@api_version=v1
@base_url={{protocol}}://{{host}}:{{port}}/api/{{api_version}}



#======================================Get all======================================

###
GET {{base_url}}/roles/ HTTP/1.1
###
GET {{base_url}}/users/ HTTP/1.1
###
GET {{base_url}}/organizations/ HTTP/1.1
###
GET {{base_url}}/analyzes/ HTTP/1.1
###
GET {{base_url}}/files/ HTTP/1.1
###
GET {{base_url}}/reports/ HTTP/1.1
###
GET {{base_url}}/visualizations/ HTTP/1.1


//======================================Roles api======================================

###
POST {{base_url}}/roles/ HTTP/1.1
content-type: application/json

{
    "name": "User",
    "description": "Role for admin user"
}

###
GET {{base_url}}/roles/ HTTP/1.1

### Get by name
GET {{base_url}}/roles?name=Admin HTTP/1.1

### Get by ID
GET {{base_url}}/roles/1 HTTP/1.1

###
PUT {{base_url}}/roles/1 HTTP/1.1
content-type: application/json

{
    "name": "User",
    "description": "Role for standart user"
}

###
DELETE {{base_url}}/roles/34 HTTP/1.1



//======================================Users api======================================
###
POST {{base_url}}/users/ HTTP/1.1
content-type: application/json

  {
    "first_name": "Sam",
    "second_name": "Lun",
    "email": "sam2@mail.com",
    "phone": "+38018811289",
    "username": "sam2",
    "password": "sam123",
    "role_id": 1
  }

###
GET {{base_url}}/users/ HTTP/1.1

###
GET {{base_url}}/users/?name=User HTTP/1.1
###
GET {{base_url}}/users/2 HTTP/1.1
###
GET {{base_url}}/users/2/organizations HTTP/1.1
###
GET {{base_url}}/users/2/files HTTP/1.1
###
GET {{base_url}}/users/2/reports HTTP/1.1
###
POST {{base_url}}/users/login HTTP/1.1
content-type: application/json

  {
    "username": "don",
    "password": "don123"
  }


###
GET {{base_url}}/users/ HTTP/1.1
###
PUT {{base_url}}/users/8 HTTP/1.1
content-type: application/json

  {
    "first_name": "Sam",
    "second_name": "Fisher",
    "email": "sam2@mail.com",
    "phone": "+380132123126",
    "username": "sam2",
    "password": "sam1234",
    "role_id": 1
  }

###
DELETE {{base_url}}/users/8 HTTP/1.1
###
GET {{base_url}}/users/2/organizations HTTP/1.1




//======================================Organizations api======================================
###
GET {{base_url}}/organizations/ HTTP/1.1
###
GET {{base_url}}/organizations/1 HTTP/1.1
###
GET {{base_url}}/organizations/1/users HTTP/1.1
###
GET {{base_url}}/organizations/user/2 HTTP/1.1

###
GET {{base_url}}/organizations/2/files HTTP/1.1

###
GET {{base_url}}/organizations/2/reports HTTP/1.1

###
POST {{base_url}}/organizations/?user_id=1 HTTP/1.1
content-type: application/json

  {
    "name": "Admins",
    "description": "Admins org",
    "email": "admns@gmail.com",
    "phone": "+32342341337"
  }

###
GET {{base_url}}/organizations/ HTTP/1.1
###
PUT {{base_url}}/organizations/2 HTTP/1.1
content-type: application/json

  {
    "name": "Macdonalds2",
    "description": "The Fastfood restouran",
    "email": "mac2@gmail.com",
    "phone": "+38011231321"
  }

###
DELETE {{base_url}}/organizations/8 HTTP/1.1
###
POST  {{base_url}}/organizations/users HTTP/1.1
content-type: application/json

  {
    "user_id": 2,
    "organization_id": 1,
    "organization_role_id": 1
  }
###
DELETE {{base_url}}/organizations/1/user/2 HTTP/1.1




//======================================organizationRoles api======================================
###
GET {{base_url}}/organizations/1/roles/ HTTP/1.1

###
GET {{base_url}}/organizations/1/roles/1 HTTP/1.1

###
POST {{base_url}}/organizations/1/roles/ HTTP/1.1
content-type: application/json

{
    "name": "Admin ",
    "description": "Role for admin user"
}
###
PUT {{base_url}}/organizations/1/roles/1 HTTP/1.1
content-type: application/json

{
    "name": "Admin",
    "description": "Role for admin user"
}

###
DELETE {{base_url}}/organizations/roles/3 HTTP/1.1




//====================================== OrganizationsMembers api======================================
###
GET {{base_url}}/organizations/1/members/ HTTP/1.1
###
GET {{base_url}}/organizations/1/members/1 HTTP/1.1
###
GET {{base_url}}/organizations/1/members/1/role HTTP/1.1


//======================================Fiels api======================================
###
GET {{base_url}}/files/ HTTP/1.1

###
GET {{base_url}}/files/1 HTTP/1.1
###
GET {{base_url}}/files/download/1 HTTP/1.1

# ###
# POST {{base_url}}/files/upload/ HTTP/1.1
# content-type: application/json

#   {
#     "name": "TheName",
#     "file_path": "Bonder3",
#     "user_id": 2,
#     "organization_id": 1
#   }
###
POST {{base_url}}/files/upload?name=MyFile&user_id=1&organization_id=1 HTTP/1.1
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"

file
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="file.csv"

< ./file.csv
--WebAppBoundary--

###
PUT {{base_url}}/files/2 HTTP/1.1
content-type: application/json

  {
    "id": 2,
    "name": "TheName22",
    "file_path": "Bonder2",
    "user_id": 1,
    "organization_id": 1
  }

###
DELETE {{base_url}}/files/1 HTTP/1.1





//======================================Reports api======================================
###
GET {{base_url}}/reports/ HTTP/1.1

###
GET {{base_url}}/reports/1 HTTP/1.1

###
GET {{base_url}}/reports/1/analyzes HTTP/1.1

###
GET {{base_url}}/reports/1/visualizations HTTP/1.1

###
POST {{base_url}}/reports/ HTTP/1.1
content-type: application/json

  {
    "name": "TheFirstReport3",
    "data_points": "the moste important report ever",
    "user_id": 2,
    "organization_id": 1
  }

###
PUT {{base_url}}/reports/1 HTTP/1.1
content-type: application/json

  {
    "name": "TheFirstReport",
    "data_points": "The moste important report ever",
    "user_id": 1,
    "organization_id": 1
  }

###
DELETE {{base_url}}/reports/3 HTTP/1.1





//======================================Analyzes api======================================
###
GET {{base_url}}/analyzes/ HTTP/1.1

###
GET {{base_url}}/analyzes/4 HTTP/1.1
###
GET {{base_url}}/analyzes/download/2 HTTP/1.1

###
POST  {{base_url}}/analyzes/?id=1 HTTP/1.1
content-type: application/json

  # {
  #   "name": "TheFirstReport3",
  #   "description": "the moste important report ever",
  #   "support": 0.1,
  #   "lift": 0.1,
  #   "confidence": 0.1,
  #   "rules_length": 1,
  #   "report_id": 1
  # }
  {
    "name": "TheFirstReport3",
    "description": "the moste important report ever",
    "support": 0.01,
    "lift": 0.01,
    "confidence": 0.01,
    "rules_length": 3,
    "report_id": 1
  }

###
PUT {{base_url}}/analyzes/1 HTTP/1.1
content-type: application/json

  {
    "name": "First analyze",
    "description": "the moste important analyze ever",
    "support": 0.1,
    "lift": 0.1,
    "confidence": 0.1,
    "rules_length": 3,
    "report_id": 1
  }

###
DELETE {{base_url}}/analyzes/3 HTTP/1.1





//======================================Visualizations api======================================
###
GET {{base_url}}/visualizations/ HTTP/1.1
###
GET {{base_url}}/visualizations/1 HTTP/1.1
###
GET {{base_url}}/visualizations/data/4 HTTP/1.1
###
GET {{base_url}}/visualizations/download/4 HTTP/1.1

###
POST {{base_url}}/visualizations/ HTTP/1.1
content-type: application/json

  {
    "name": "first visualization",
    "report_id": 1
  }

###
PUT {{base_url}}/visualizations/1 HTTP/1.1
content-type: application/json

  {
    "name": "First visualization",
    "image_file_path": "The most important visualization ever",
    "report_id": 1
  }

###
DELETE {{base_url}}/visualizations/1 HTTP/1.1