@protocol=http
@host=localhost
@port=8000




//======================================Roles api======================================
###
GET {{protocol}}://{{host}}:{{port}}/api/roles/ HTTP/1.1

###
GET {{protocol}}://{{host}}:{{port}}/api/roles/3 HTTP/1.1
###
GET {{protocol}}://{{host}}:{{port}}/api/roles/User HTTP/1.1

###
POST {{protocol}}://{{host}}:{{port}}/api/roles/ HTTP/1.1
content-type: application/json

{
    "name": "Admin2",
    "description": "Role for admin user"
}

###
GET {{protocol}}://{{host}}:{{port}}/api/roles/4 HTTP/1.1
###
PUT {{protocol}}://{{host}}:{{port}}/api/roles/4 HTTP/1.1
content-type: application/json

{
    "name": "User2",
    "description": "Role for standart user"
}

###
DELETE {{protocol}}://{{host}}:{{port}}/api/roles/4 HTTP/1.1





//======================================organizationRoles api======================================
###
GET {{protocol}}://{{host}}:{{port}}/api/organization_roles/ HTTP/1.1

###
GET {{protocol}}://{{host}}:{{port}}/api/organization_roles/1 HTTP/1.1

###
POST {{protocol}}://{{host}}:{{port}}/api/organization_roles/ HTTP/1.1
content-type: application/json

{
    "name": "Admin ",
    "description": "Role for admin user"
}
###
GET {{protocol}}://{{host}}:{{port}}/api/organization_roles/ HTTP/1.1
###
PUT {{protocol}}://{{host}}:{{port}}/api/organization_roles/2 HTTP/1.1
content-type: application/json

{
    "name": "Admin",
    "description": "Role for admin user"
}

###
DELETE {{protocol}}://{{host}}:{{port}}/api/organization_roles/3 HTTP/1.1





//======================================Users api======================================
###
GET {{protocol}}://{{host}}:{{port}}/api/users/ HTTP/1.1
###
GET {{protocol}}://{{host}}:{{port}}/api/users/?name=User HTTP/1.1
###
GET {{protocol}}://{{host}}:{{port}}/api/users/2 HTTP/1.1
###
GET {{protocol}}://{{host}}:{{port}}/api/users/2/organizations HTTP/1.1
###
GET {{protocol}}://{{host}}:{{port}}/api/users/2/files HTTP/1.1
###
GET {{protocol}}://{{host}}:{{port}}/api/users/2/reports HTTP/1.1
###
POST {{protocol}}://{{host}}:{{port}}/api/users/login HTTP/1.1
content-type: application/json

  {
    "username": "don",
    "password": "don123"
  }

###
POST {{protocol}}://{{host}}:{{port}}/api/users/ HTTP/1.1
content-type: application/json

  {
    "first_name": "Sam",
    "second_name": "Lun",
    "email": "sam2@mail.com",
    "phone": "+38018811289",
    "username": "sam2",
    "password": "sam123",
    "role_id": 1
  }
###
GET {{protocol}}://{{host}}:{{port}}/api/users/ HTTP/1.1
###
PUT {{protocol}}://{{host}}:{{port}}/api/users/8 HTTP/1.1
content-type: application/json

  {
    "first_name": "Sam",
    "second_name": "Fisher",
    "email": "sam2@mail.com",
    "phone": "+380132123126",
    "username": "sam2",
    "password": "sam1234",
    "role_id": 1
  }

###
DELETE {{protocol}}://{{host}}:{{port}}/api/users/8 HTTP/1.1
###
GET {{protocol}}://{{host}}:{{port}}/api/users/2/organizations HTTP/1.1




//======================================Organizations api======================================
###
GET {{protocol}}://{{host}}:{{port}}/api/organizations/ HTTP/1.1
###
GET {{protocol}}://{{host}}:{{port}}/api/organizations/1 HTTP/1.1
###
GET {{protocol}}://{{host}}:{{port}}/api/organizations/3/users HTTP/1.1
###
GET {{protocol}}://{{host}}:{{port}}/api/organizations/user/2 HTTP/1.1

###
GET {{protocol}}://{{host}}:{{port}}/api/organizations/2/files HTTP/1.1

###
GET {{protocol}}://{{host}}:{{port}}/api/organizations/2/reports HTTP/1.1

###
POST {{protocol}}://{{host}}:{{port}}/api/organizations/?user_id=2 HTTP/1.1
content-type: application/json

  {
    "name": "Admins",
    "description": "Admins org",
    "email": "admns@gmail.com",
    "phone": "+32342341337"
  }

###
GET {{protocol}}://{{host}}:{{port}}/api/organizations/ HTTP/1.1
###
PUT {{protocol}}://{{host}}:{{port}}/api/organizations/2 HTTP/1.1
content-type: application/json

  {
    "name": "Macdonalds2",
    "description": "The Fastfood restouran",
    "email": "mac2@gmail.com",
    "phone": "+38011231321"
  }

###
DELETE {{protocol}}://{{host}}:{{port}}/api/organizations/8 HTTP/1.1
###
POST  {{protocol}}://{{host}}:{{port}}/api/organizations/users HTTP/1.1
content-type: application/json

  {
    "user_id": 2,
    "organization_id": 1,
    "organization_role_id": 1
  }
###
DELETE {{protocol}}://{{host}}:{{port}}/api/organizations/1/user/2 HTTP/1.1


//======================================Users organizations api======================================
###
GET {{protocol}}://{{host}}:{{port}}/api/users_organizations/ HTTP/1.1
###
GET {{protocol}}://{{host}}:{{port}}/api/users_organizations/?user_id=1&organization_id=1 HTTP/1.1
###
GET {{protocol}}://{{host}}:{{port}}/api/users_organizations/role?user_id=1&organization_id=1 HTTP/1.1


//======================================Fiels api======================================
###
GET {{protocol}}://{{host}}:{{port}}/api/files/ HTTP/1.1

###
GET {{protocol}}://{{host}}:{{port}}/api/files/1 HTTP/1.1
###
GET {{protocol}}://{{host}}:{{port}}/api/files/download/1 HTTP/1.1

# ###
# POST {{protocol}}://{{host}}:{{port}}/api/files/upload/ HTTP/1.1
# content-type: application/json

#   {
#     "name": "TheName",
#     "file_path": "Bonder3",
#     "user_id": 2,
#     "organization_id": 1
#   }
###
POST {{protocol}}://{{host}}:{{port}}/api/files/upload?name=MyFile&user_id=1&organization_id=1 HTTP/1.1
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"

file
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="file.csv"

< ./file.csv
--WebAppBoundary--

###
PUT {{protocol}}://{{host}}:{{port}}/api/files/2 HTTP/1.1
content-type: application/json

  {
    "id": 2,
    "name": "TheName22",
    "file_path": "Bonder2",
    "user_id": 1,
    "organization_id": 1
  }

###
DELETE {{protocol}}://{{host}}:{{port}}/api/files/1 HTTP/1.1





//======================================Reports api======================================
###
GET {{protocol}}://{{host}}:{{port}}/api/reports/ HTTP/1.1

###
GET {{protocol}}://{{host}}:{{port}}/api/reports/1 HTTP/1.1

###
GET {{protocol}}://{{host}}:{{port}}/api/reports/1/analyzes HTTP/1.1

###
GET {{protocol}}://{{host}}:{{port}}/api/reports/1/visualizations HTTP/1.1

###
POST {{protocol}}://{{host}}:{{port}}/api/reports/ HTTP/1.1
content-type: application/json

  {
    "name": "TheFirstReport3",
    "data_points": "the moste important report ever",
    "user_id": 2,
    "organization_id": 1
  }

###
PUT {{protocol}}://{{host}}:{{port}}/api/reports/1 HTTP/1.1
content-type: application/json

  {
    "name": "TheFirstReport",
    "data_points": "The moste important report ever",
    "user_id": 1,
    "organization_id": 1
  }

###
DELETE {{protocol}}://{{host}}:{{port}}/api/reports/3 HTTP/1.1





//======================================Analyzes api======================================
###
GET {{protocol}}://{{host}}:{{port}}/api/analyzes/ HTTP/1.1

###
GET {{protocol}}://{{host}}:{{port}}/api/analyzes/4 HTTP/1.1
###
GET {{protocol}}://{{host}}:{{port}}/api/analyzes/download/2 HTTP/1.1

###
POST  {{protocol}}://{{host}}:{{port}}/api/analyzes/?id=1 HTTP/1.1
content-type: application/json

  # {
  #   "name": "TheFirstReport3",
  #   "description": "the moste important report ever",
  #   "support": 0.1,
  #   "lift": 0.1,
  #   "confidence": 0.1,
  #   "rules_length": 1,
  #   "report_id": 1
  # }
  {
    "name": "TheFirstReport3",
    "description": "the moste important report ever",
    "support": 0.01,
    "lift": 0.01,
    "confidence": 0.01,
    "rules_length": 3,
    "report_id": 1
  }

###
PUT {{protocol}}://{{host}}:{{port}}/api/analyzes/1 HTTP/1.1
content-type: application/json

  {
    "name": "First analyze",
    "description": "the moste important analyze ever",
    "support": 0.1,
    "lift": 0.1,
    "confidence": 0.1,
    "rules_length": 3,
    "report_id": 1
  }

###
DELETE {{protocol}}://{{host}}:{{port}}/api/analyzes/3 HTTP/1.1





//======================================Visualizations api======================================
###
GET {{protocol}}://{{host}}:{{port}}/api/visualizations/ HTTP/1.1
###
GET {{protocol}}://{{host}}:{{port}}/api/visualizations/1 HTTP/1.1
###
GET {{protocol}}://{{host}}:{{port}}/api/visualizations/data/4 HTTP/1.1
###
GET {{protocol}}://{{host}}:{{port}}/api/visualizations/download/4 HTTP/1.1

###
POST {{protocol}}://{{host}}:{{port}}/api/visualizations/ HTTP/1.1
content-type: application/json

  {
    "name": "first visualization",
    "report_id": 1
  }

###
PUT {{protocol}}://{{host}}:{{port}}/api/visualizations/1 HTTP/1.1
content-type: application/json

  {
    "name": "First visualization",
    "image_file_path": "The most important visualization ever",
    "report_id": 1
  }

###
DELETE {{protocol}}://{{host}}:{{port}}/api/visualizations/1 HTTP/1.1