"""v1.0.0

Revision ID: def1de3d6e3d
Revises: 
Create Date: 2023-11-22 20:07:56.799781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def1de3d6e3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('SCHEDULED', 'STARTED', 'IN_PROGRESS', 'FINISHED', 'FAILED', name='analyzestatus'), nullable=False))
        batch_op.add_column(sa.Column('started_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('finished_date', sa.DateTime(), nullable=False))

    with op.batch_alter_table('datasources', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.Enum('FILE', 'DB', 'CSV', 'SQLITE', 'MYSQL', 'POSTGRESQL', name='datasourcetypes'),
               existing_nullable=False)

    with op.batch_alter_table('visualizations', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.Enum('FILE', 'DATA_POINTS', name='visualizationtypes'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visualizations', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('FILE', 'DATA_POINTS', name='visualizationtypes'),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)

    with op.batch_alter_table('datasources', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('FILE', 'DB', 'CSV', 'SQLITE', 'MYSQL', 'POSTGRESQL', name='datasourcetypes'),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)

    with op.batch_alter_table('analyzes', schema=None) as batch_op:
        batch_op.drop_column('finished_date')
        batch_op.drop_column('started_date')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
